{ modulesPath, ... }:
{

  # This file was auto-generated by nix-infect. Copy yours from
  # /etc/nixos/hardware-configuration.nix on the infected if it differs
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];
  boot.loader.grub.device = "/dev/vda";
  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "xen_blkfront" "vmw_pvscsi" ];
  boot.initrd.kernelModules = [ "nvme" ];
  fileSystems."/" = { device = "/dev/vda3"; fsType = "ext4"; };

}
